version: "3.9"
services:
  vault-server:
    image: vault:latest
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - ./vault/config:/vault/config
      - ./vault/data:/vault/data
      - ./vault/file:/vault/file
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
    command:
      - "server"
    networks:
      - vault-network

  vault-client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - vault.uri=http://vault-server:8200
      - vault.token=hvs.JJU8AvvlUXuVOMVXVaasgVXv
    depends_on:
      - vault-server
    networks:
      - vault-network
  mysql:
    image: mysql:8.0
    container_name: example_mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1q2w3e4r
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    networks:
      - vault-network
  redis:
    image: redis:3
    container_name: example_redis
    ports:
      - "6379:6379"
    networks:
      - vault-network
networks:
  vault-network:
    driver: bridge