spring:
  jpa:
    database: mysql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
vault:
  uri: ${VAULT_URI}
  token: ${VAULT_TOKEN}
  path:
    datasource: ${VAULT_DATASOURCE_PATH:kv/data/db/mysql}
    redis: ${VAULT_REDIS_PATH:kv/data/db/redis}